### ISSUE TITLE
[BUG] Captions are turned off when user changes audio quality selection in various browsers and devices

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#404] opened 2024-02-09 19:39 UTC
# Description

In Chrome, when the user turns on captions, then changes the selection in the audio quality, the captions disappear. Sometimes, they don't disappear until user selects 2 options in quality selector. The captions may be turned off, but the green underline still appears under the CC icon. Captions cannot be re-enabled until page is reloaded.

This problem is happening in Chrome on computer, but not Safari. We see this issue in Safari on iPad, but not Chrome. I have not been able to replicate this in Chrome on an iPad. It is also happening on Android.

# To reproduce
1. Start playback of a video item with captions (example: https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t)
2. Turn on captions
3. Change quality from 'auto' to one of the other options
4. If captions are still displaying, try changing quality to a different option
5. Captions disappear. CC icon retains green line, but if mouse-over it shows 'captions off' as selected.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c873da5ac89707ed12353f559b3d08a2d9af642/Screen%20Recording%202024-02-09%20at%202.27.06%20PM.mov)

**Comment by joncameron** [comment] 2024-02-12 14:48
Needs retesting.

**Comment by joncameron** [comment] 2024-03-06 19:22
Duplicate of #5651

**Comment by joncameron** [comment] 2024-03-07 18:17
See https://github.com/avalonmediasystem/avalon/issues/5651

**Closed** 2024-03-07 18:17 UTC
Labels: bug 🐛
