### ISSUE TITLE
New Media Streams Not Loading in Player

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#249] opened 2023-09-27 18:03 UTC
# Description
When using a new manifest address, the player still retains the default Lunchroom Manners video.

# To Reproduce
- Go to ramp.avalonmediasystem.org
- Enter "https://media.dlib.indiana.edu/media_objects/jw827k39c/manifest.json" and click "Set Manifest"
- The lunchroom manners default video still displays, and structure links seek to points in the Lunchroom Manners media loaded in the player, rather than loading the appropriate streams from the manifest

# Environment
- ramp.avalonmediasystem.org

**Comment by joncameron** [comment] 2023-09-27 19:10
Potentially related to null values in the metadata within manifests.

**Comment by masaball** [comment] 2023-10-03 15:34
I have been unable to reproduce this bug. Seems to have been resolved by some of the other work that was recently done?

**Closed** 2023-10-03 17:30 UTC
Labels: bug 🐛
