### ISSUE TITLE
Don't Scroll Page on Transcript Component Cue Advance

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#514] opened 2024-06-05 16:22 UTC
## Description
The Transcript component will scroll the page to fit as much of the component into view as possible on each cue change when set to auto-advance. 
### Example
![Jun-05-2024 12-20-28](https://github.com/samvera-labs/ramp/assets/1406618/d810d98b-0f73-4ffa-afff-30e71bf0a035)

### When Transcript Component is Partially in View
![Jun-07-2024 12-09-48](https://github.com/samvera-labs/ramp/assets/1406618/dbf568fd-d0cb-4b40-b09a-edf74f7b4aca)

Currently users can be in a situation where the viewport has the video player and most of the transcript component, but when a cue advances the page is automatically scrolled and creates a jarring effect. It also forces a long scroll away from the media player when cues change and the viewport is narrow enough that the transcript component is at the bottom of the page elements.

## Done Looks Like
- [ ] Transcript component does not scroll the page when advancing to the next cue (only content within the component scrolls)

**Comment by elynema** [comment] 2024-06-06 23:56
@joncameron I'm pretty sure this is by design. You need to turn off the auto-scroll first.

**Comment by joncameron** [comment] 2024-06-07 21:14
I'll refine this issue since I feel this behavior should change. Auto-scroll should be scrolling the transcript component, not scrolling the page itself to move the transcript component into view (or at least not by default).

Currently you can be in a situation where the viewport has the video player and most of the transcript component, but when a cue advances the page is automatically scrolled and creates a jarring effect. It also forces a long scroll away from the media player when cues change and the viewport is narrow enough that the transcript component is at the bottom of the page elements.

his doesn't appear to apply or be functioning in this way on avalon-dev as Chris mentioned.

**Comment by elynema** [comment] 2024-06-25 21:57
This is particularly prominent on mobile devices, where you can't watch the video is the transcript is auto-scrolling. Need to QA this with a new Ramp build in Avalon on a mobile device.

**Comment by elynema** [comment] 2024-06-28 18:45
@charumitraravi Can you QA this one on avalon-dev? This is particularly obvious on mobile devices, where you usually can't see the media player if you are looking at the transcript. If you start playback with the Transcript component selected, you should be able to scroll up to view the media item without the screen auto-scrolling back down to the transcript component as the transcript auto-advances.

**Comment by charumitraravi** [comment] 2024-07-01 16:29
QA completed. Checked on mobile devices, as well as web browser with different view ports. The fix is working as expected.

**Comment by elynema** [comment] 2024-07-03 19:18
Double-checked on Android, working great, closing.

**Closed** 2024-07-03 19:18 UTC
