### ISSUE TITLE
Upgrade VideoJS to 8.0 or latest stable version

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/ramp#401] opened 2024-02-09 18:37 UTC
### Description

Video.js version in Ramp has been pinned to 7.* because it needed Video.js to be that version to use the quality selector plugin used in Ramp.
Ramp was waiting on https://github.com/silvermine/videojs-quality-selector/pull/93 to be merged and released to upgrade Video.js. Now that it has been merged and released `@silvermine/videojs-quality-selector` can be upgraded from  1.2.4 to 1.3.1 which is the latest version of the plugin. And subsequently Video.js can be upgraded from 7.* to 8.*

### Done Looks Like
- [x] `@silvermine/videojs-quality-selector` upgraded to 1.3.1
- [x] `videoj.js` upgraded to latest stable 8.* version
- [x] VideoJSFileDownload component's code changes to use `extends` instead of `videojs.extend(..`
- [ ] Test all the custom VideoJS components (Progressbar, previous/next canvas buttons, current time display in progress bar, zoom scrubber (magnifying glass), file download) works as expected in all supported browsers and devices
- [ ] Test all the other customization Ramp has implemented on top of native VideoJS functionalities work as expected in all supported browsers and devices: Chrome on Android, Safari on iPhone and iPad, Chrome and Safari on desktop

**Comment by joncameron** [comment] 2024-02-12 14:55
This can be worked on after 7.7 release; will require a retest across media player test cases since this will be a large change.

**Comment by joncameron** [comment] 2024-03-06 19:29
Most of the work here will be testing; custom components should all be tested for functionality.

**Comment by Dananji** [comment] 2024-04-22 13:51
This work has been deployed to Ramp demo site

**Comment by joncameron** [comment] 2024-05-13 16:25
Need to update test cases in Testomat.io to make sure all of the areas mentioned in this ticket are represented.

**Comment by elynema** [comment] 2024-06-13 20:44
@charumitraravi This should be able to be tested on avalon-dev. The QA specifically covers the custom components that have been added to Ramp (file download is only available on the Ramp demo site). But it would be good to note that all functionality in the player is working. This is good preparation as we move into regression to QA this well, and I don't think it has been tested yet.

**Comment by charumitraravi** [comment] 2024-06-20 17:18
Tested all the facets in the media player (forward, backward, pause, scrubber movements, captions, magnifying glass,volume,quality,speed and download in ramp site)and the hotkeys, across the web (chrome,safari) , iphone , ipad (safari) and android(chrome) in different orientations and in full screen . 

- Caption is switched on by default. If I switch off the captions, the selection is not remembered when the player advances to the next section of the item. 
- Transcripts are not getting auto scrolled when the video progresses (8th section in this [item](https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p))
- [iOS] - scrubber movement is not working

**Comment by elynema** [comment] 2024-06-25 21:58
@charumitraravi 

- We have an issue (#5651) to make the caption settings sticky. They are not currently sticky across canvases, so this is not a new bug to report.
- You said transcripts are not getting auto scrolled when the video progresses. I tested the item you linked, and it is working for me in Chrome. It is a very weird transcript with multiple cues for the same second, so it is scrolling through very fast. Do you have any other examples where this is not working? Or is it in a different browser?
- For scrubbing on iOS, I can confirm this is not working properly in the native player. This seems to be resolved in #516, which is on the demo site, so we can QA that again once we get a new Ramp build on avalon-dev to see if it is resolved.
- I'm not able to replicate the issue with pause/play on Android. Have you run into this in Browserstack or on a physical device? I wasn't aware that we supported double tap to full screen. Did this work previously?
- The transcript auto-scroll should be handled in #514.
- The only time I've seen an issue with add to playlist and create thumbnail buttons being disabled is when the media player loads more slowly than usual. That's probably a timing issue for events. Do you have an example that reliably creates problems so I can create an issue? So far, I've only found this one that sometimes doesn't work: https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t

**Comment by charumitraravi** [comment] 2024-06-26 15:47
@elynema 
- As discussed in the meeting, We aren't supporting double tap to full screen. However, there is some flakiness around single tap on screen to pause/ play which is observed on avalon staging as well, which looks like an existing issue.  
- The transcript auto scroll issue is'nt happening anymore on my browser too (which is strange, since i was consistently able to replicate it last week) on the item I specified, and some other items as well. I will keep trying and update on this thread if I am able to find something.
- Thumbnail buttons and Add to playlist  button seems to be resolved now.

**Comment by elynema** [comment] 2024-06-26 16:15
Charu said that the pause/play issue is having when tapping 4-5 times in the same spot on the video on Android. I haven't been able to replicate in Browserstack, so probably won't create an issue for this. She confirmed that we have not historically supported double tap to full screen in Avalon on Android.

Created #5885 to track issues with the add to playlist, thumbnail, and timeline buttons being disabled on mobile.

**Comment by elynema** [comment] 2024-06-26 16:16
@charumitraravi Did you have any additional feedback on the transcript not auto-scrolling to add for further troubleshooting?

I will note that transcript auto-scroll is turned off automatically if you enter a search term in the Transcript tab to search the transcript. This is because we can't have the transcript auto-scroll at the same time the user is navigating search results in the transcript. This is something we'll be working on improving in the future; not sure if it might have caused the problem you're reporting.

**Closed** 2024-06-26 18:41 UTC

**Comment by charumitraravi** [comment] 2024-06-26 18:56
@elynema 
I don't have any additional feedback to add upon the transcript not auto-scrolling issue. I was only able to replicate the issue when I enter a search term , like you mentioned.
