### ISSUE TITLE
Manifests with ranges with empty `items` arrays fail to parse and load

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/ramp#217] opened 2023-08-16 15:25 UTC
**Describe the bug**
Manifests with ranges with empty `items` arrays fail to parse and load. 

**To Reproduce**
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
2. Open developer console in browser to see error

**Expected behavior**
Manifests with ranges with no children should still parse and display but not be actionable since they have no linked canvas.

**Additional context**
See https://github.com/avalonmediasystem/avalon/issues/5141 for previous discussion in avalon

# Done Looks Like
- [x] Ramp still renders when manifests contain ranges with no children (Fix parsing)
- [x] All canvases (sections in Avalon) should be listed in the structured navigation, even if they do not have any sub-elements
- [ ] Add handling in Avalon to catch when React fails to create the component (avoid element flopping effect)

**Comment by Dananji** [comment] 2023-09-07 17:45
I went through the spec and noticed this under the [Ranges](https://iiif.io/api/presentation/3.0/#54-range);

`All of the Canvases or parts that should be considered as being part of a Range must be included within the Range’s items property, or a descendant Range’s items.`

Right now we don't have Canvas information under a Range, when it is childless. I wasn't sure whether this statement applies to the childless divs we have in Avalon manifests. So, I wanted to see what others think and understand from this.

For a section (masterfile) without adding any structure;
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0o2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8377a83a6e75d77cf52e1f983939b5c4ecf155fb/image.png)
Avalon generates the following under structures:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1Y2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0387c42967aee5ec194b2bbc8ba73932f1eb0dca/image.png)

For a section (masterfile) with childless divs;
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0I2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--203da69431cd4d26e8f7464374cc8aff820ce830/image.png)
Avalon generates the following under structures;
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2Q2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ce2047c105df654fdcd6a41d36dfe976b3f3705e/image.png)
And it doesn't have Canvas related information under the Range.

For the fix I worked in this bug, I used the Canvas information from the `items` array using `canvasIndex` to fill in the necessary Canvas related information required for structured navigation. 

This works for Avalon's manifests because they always have ranges in the same order of the Canvases in the `items` array. But there can be manifests without one-to-one mapping between ranges in the `structures` and canvases in the `items` and the way the Ramp displays them will mis-interpret what's in the Manifest.

**Comment by joncameron** [comment] 2023-09-13 13:57
Example of a single childless div: https://avalon-dev.dlib.indiana.edu/media_objects/b5644r534/manifest.json

**Comment by elynema** [comment] 2023-09-19 13:43
See #5350 for the solution that was implemented.

**Comment by elynema** [comment] 2023-10-05 20:42
Closing this as #5350 was implemented. We have a new ticket #5368 to try to address the issues caused by childless divs in the structure.

**Closed** 2023-10-05 20:42 UTC
