### ISSUE TITLE
Show Player Controls and Duration Remaining for Inaccessible Canvas while Fullscreen

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/ramp#501] opened 2024-05-16 20:56 UTC
## Description
When in fullscreen on an item or playlist with multiple canvases, switching to an inaccessible item will retain fullscreen and show the standard "you don't have permission to play" text for a duration, after which the next canvas is loaded. However, there is no indicator that the player will automatically move on after a period of time, and the media player controls do not display. 

Ramp should retain player controls for inaccessible item display, and a timer is displayed to the user to indicate that autoplay will continue after a set duration. We already have the timer set as part of the inaccessible item handling in the media player, and that value could be presented in the UI.

## Done Looks Like
- [ ] Ramp retains player control visibility and behavior when showing an inaccessible item (revert Video.js changes)
- [ ] Timer displays as duration and progress shows timer state (i.e. as if a 10 second long item is playing)
- [ ] Auto-play resumes in Safari after playback moves on to the next item

**Comment by joncameron** [comment] 2024-05-21 15:29
Would be better/easier to move straight to the enhancement version of this, where player controls are retained for inaccessible items and a timer is displayed to the user to indicate that autoplay will continue after a set amount. 

We already have the timer set, and that value could be presented in the UI. This could be as simple as reverting Video.js changes to make sure player controls aren't hidden during this. 

@joncamer to create a new issue or change this one to reflect the change in scope. This new issue would be 2 points.

**Comment by elynema** [comment] 2024-06-13 21:30
Note that in Safari, when in full-screen playback, after the 10 seconds of an inaccessible item, it attempts to load the next item but auto-playback does not start. This works fine in Chrome.

**Comment by Dananji** [comment] 2024-06-17 17:57
I was not able to reproduce the full-screen auto advance issue on Safari on both Ramp demo site and in avalon-dev for [this playlist](https://avalon-dev.dlib.indiana.edu/playlists/45). Was this happening in a specific playlist?

**Comment by Dananji** [comment] 2024-06-18 14:05
I was not able to use player controls to show the 10 second duration as described in the done looks like; the reason for this is when there's an inaccessible item as the first item in the manifest there's no Video.js instance. To create a Video.js instance at least one source URL is needed to be provided for the HTML5 video tag. And for inaccessible items sources list is empty.
Instead I opted to show the 10 second timer like it is shown in Youtube;
![auto-advance-preview](https://github.com/samvera-labs/ramp/assets/1331659/99b65bbc-12fc-4f2f-9c04-cac05953af99)

**Comment by Dananji** [comment] 2024-06-20 15:51
Notes on the current implementation;
- [ ] Only display 'Next' button when first item on the list is inaccessible
- [ ] Only display 'Previous' button when the last item on the list is inaccessible
- [ ] Display both 'Previous' and 'Next' buttons when the inaccessible item is in between items
- [ ] Toggling 'Auto Advance' from off -> on; re-starts timer from 10 seconds (identical to the code-side behavior we had for the message display)
- [ ] When timer ends, the next item is loaded into the player
- [ ] When user clicks on another inaccessible item when an inaccessible item is displayed, the timer resets to 10 seconds
When 'Auto Advance' toggle is turned off;
- [ ] Stops the timer
- [ ] Dims the timer display
- [ ] Displays 'Previous'/'Next' buttons appropriately

**Comment by joncameron** [comment] 2024-07-02 16:07
I think what Emily wrote is the expected behavior: `as you hit play on any playlist item, all following items should begin playback automatically if 'auto-play' is turned on for the playlist`, and this is a bug. Interaction with the player controls or navigation shouldn't change the state of autoplay.

Same for the other issue with content that won't load or play—this could be a separate bug issue unless it's the same problem as is causing the grayed out inaccessible item issue. I agree that the first one makes sense as part of this issue.

**Comment by joncameron** [comment] 2024-07-02 18:39
Needs testing in Safari before closing.

**Comment by elynema** [comment] 2024-07-03 19:39
Tested in full-screen on iPad, Android, and Chrome now as well.

Note that when auto-play is turned off, the timer countdown does not display (rather than being dimmed), which is fine.

Closing this as issues with moving back and forth moved to Ramp #548.

**Closed by elynema** 2024-07-03 19:39 UTC

**Comment by Dananji** [comment] 2024-07-03 20:45
When auto-play is turned off the countdown does not display is the correct behavior. This was changed during code review process. Please see the discussion in the PR: https://github.com/samvera-labs/ramp/pull/529.

 Sorry for the inconvenience, I forgot to update the done looks like in the ticket.

**Comment by elynema** [comment] 2024-07-03 20:54
Yes, I was just noting the change to the requirements in this issue.

**Comment by joncameron** [comment] 2024-07-05 13:15
Follow-on tickets: samvera-labs/ramp#548 and samvera-labs/ramp#551
